#!/bin/sh

source config

for battery in /sys/class/power_supply/BAT?*; do
    # If non-first battery, print a space separator.
    [ -n "${capacity+x}" ] && printf " "
    # Sets up the status and capacity
    case "$(cat "$battery/status" 2>&1)" in
        "Full") status="⚡" ;;
        "Discharging") status="🔋" ;;
        "Charging") status="🔌" ;;
        "Not charging") status="🛑" ;;
        "Unknown") status="♻️" ;;
        *) exit 1 ;;
    esac
    capacity="$(cat "$battery/capacity" 2>&1)"

    if [ "$status" = "🔋" ] && [ "$capacity" -le 20 ]; then
        warn="❗"
        mpv --volume=80 "$LOW_BAT_SOUND" 1>/dev/null || notify-send --critical "$0" "$LOW_BAT_SOUND not found."
        notify-send -u critical "Low battery!" "Battery level is at $capacity%."
    fi

    printf "%s%s%d%%" "$status" "$warn" "$capacity"; unset warn
done && printf "\\n"
