#!/bin/sh

case "$(cat /sys/class/net/w*/operstate 2>/dev/null)" in
	down) wifiicon="🌐❗No network" ;;
	up) wifiicon="$(awk '/^\s*w/ { print "🌐" }' /proc/net/wireless)" ;;
esac

printf "$wifiicon$(ip route get 8.8.8.8 2>/dev/null|grep -Eo 'src [0-9.]+'|grep -Eo '[0-9.]+')"
