#!/bin/sh

if [ "$(bluetoothctl info)" != "Missing device address argument" ]; then
    icon="🎧"
else
    icon="🔊"
fi

[ "$(pamixer --get-mute)" = true ] && echo "$icon❗Muted" && exit
vol="$(pamixer --get-volume)"
echo "$icon$vol%"
