#!/usr/bin/env bash

isinstalled router.py || exit

# lvl="$(router.py)"

# [ "$lvl" -le 30 ] && notify-send -u critical "Router low battery!" "$lvl%" && echo "R: (!) $lvl%"
# [ "$lvl" -gt 30 ] && [ "$lvl" -lt 98 ] && echo "R: $lvl%"
# [ "$lvl" -gt 98 ] && echo "R: FULL $lvl%"

lvl="$(router.py)"

case $lvl in
    [0-9]|[1-2][0-9])
        notify-send -u critical "Router low battery!" "$lvl%" 
        echo "Router: LOW $lvl%"
        ;;
    [3-9][1-9]|[1-8][0-9])
        echo "Router: $lvl%"
        ;;
    9[89]|100)
        echo "Router: FULL $lvl%"
        ;;
esac
