#!/usr/bin/env bash

# shellcheck disable=SC2034

isinstalled rofi dmenu dust dunst libnotify || exit

DMENU="dmenu"
DMENU_V="dmenu -l 20"

SCRIPTS_DIR="$HOME/.local/scripts"
DEV_SCRIPTS_DIR="$DEV_SCRIPTS_DIR/dev"

VC_BACKUP="$HOME/.local/backup"
VC_BACKUP_MNT_DIR="$HOME/mnt/vc-backup"

NOTIFICATION_SOUNDS_DIR="$HOME/doc/sounds"
LOW_BAT_SOUND="$NOTIFICATION_SOUNDS_DIR/low-battery.mp3"
NET_USAGE_SOUND="$NOTIFICATION_SOUNDS_DIR/net-usage.wav"
LOW_MEM_SOUND="$NOTIFICATION_SOUNDS_DIR/low-memory.mp3"
RINGTONE="$NOTIFICATION_SOUNDS_DIR/ringtone.mp3"

run_dust() { dust -br -d 0 "$@"; }
runDust() { dust -br -d 0 "$@"; }

echoRedExit() {
    local message="${1:-An error occurred.}"
    local status="${2:-1}"
    printf '\e[1;31m%s\e[0m\n' "$message"
    exit "$status"
}

dump() {
    printf '\e[1;31m%s\e[0m\n' "$*"
    exit
}

echoRed() {
    if [ "$1" == "-n" ]; then
        echo -e "\n\e[1;31m${*:2}" "\e[0m"
    else
        echo -e "\e[1;31m$*" "\e[0m"
    fi
}

echoBlue() { 
    if [ "$1" == "-n" ]; then
        echo -e "\n\e[1;34m${*:2}" "\e[0m"
    else
        echo -e "\e[1;34m$*" "\e[0m"
    fi
}

echoGreen() { 
    if [ "$1" == "-n" ]; then
        echo -e "\n\e[1;32m${*:2}" "\e[0m"
    else
        echo -e "\e[1;32m$*" "\e[0m"
    fi
}

echoYellow() { 
    if [ "$1" == "-n" ]; then
        echo -e "\n\e[1;33m${*:2}" "\e[0m"
    else
        echo -e "\e[1;33m$*" "\e[0m"
    fi
}
