#!/usr/bin/env bash

# priorityItems="$XDG_CONFIG_HOME/dmenu-highpriority.csv"
# [[ ! -f "$priorityItems" ]] && notify-send "$0" "$priorityItems doesn't exist!"
# dmenu_run -hp "$(< $priorityItems)"

priorityItems="brave,chromium,ferdium,librewolf,firefox,obsidian,signal-desktop"
dmenu_run -hp "$priorityItems"
