#!/usr/bin/env python

import i3ipc
import sys

def focus_next():
    i3 = i3ipc.Connection()
    num = i3.get_tree().find_focused().workspace().num
    ws_nodes = i3.get_tree().find_focused().workspace().nodes
    curr = i3.get_tree().find_focused()

    ids = [win.id for win in ws_nodes if win.type == 'con']

    next_idx = (ids.index(curr.id) + 1) % len(ids)
    next_id = ids[next_idx]

    i3.command(f'focus -n #{next_id}')

def focus_prev():
    i3 = i3ipc.Connection()
    num = i3.get_tree().find_focused().workspace().num
    ws_nodes = i3.get_tree().find_focused().workspace().nodes
    curr = i3.get_tree().find_focused()

    ids = [win.id for win in ws_nodes if win.type == 'con']

    prev_idx = (ids.index(curr.id) - 1) % len(ids)
    prev_id = ids[prev_idx]

    i3.command(f'focus -p #{prev_id}')

if len(sys.argv) > 1 and sys.argv[1] == 'next':
    focus_next()
elif len(sys.argv) > 1 and sys.argv[1] == 'prev':
    focus_prev()
else:
    print("Error: no valid command provided.")
