#!/usr/bin/env bash

newMusicDir="$HOME/music/new-juice"
baseMusicDir="$HOME/music/juice-wrld"
phoneMusicDir="$HOME/mnt/phone/SD card/music/juice-wrld"

case "$1" in
    "newtophone")
        echo "Copying to phone."
        echo
        cp -vnR "$newMusicDir"/* "$phoneMusicDir"
        ;;
    "newtobase")
        echo "Copying to base dir."
        echo
        cp -vnR "${newMusicDir}"/* "$baseMusicDir"
        ;;
    "delnew")
        echo "Deleting all new songs."
        echo
        rm -vrf "${newMusicDir:?}"/*
        ;;
    *) echo "usage: newtophone/newtobase/delnew"
        ;;
esac
