#!/usr/bin/env bash

args=("$@")

MOUNT_DIR="$HOME/mnt"
[[ ! -d "$MOUNT_DIR" ]] && echo "${MOUNT_DIR} does not exist." && exit 1

isinstalled jmtpfs

checking_drives() {
  [[ -z "$(lsblk | grep sdb1)" ]] && echo "No drives detected." && exit 1
}

# Check partition type:
# lsblk -no "fstype" "/dev/sdb1"

case "${args[0]}" in
    "usb1")
        checking_drives
        sudo mount -t vfat "/dev/sdb1" "$MOUNT_DIR/usb1" -o rw,umask=0000
        ;;
    "usb2")
        checking_drives
        sudo mount -t vfat "/dev/sdb1" "$MOUNT_DIR/usb2" -o rw,umask=0000
        ;;
    # ntfs
    "ext")
        checking_drives;
        sudo mount "/dev/sdb1" "$MOUNT_DIR/ext";
        user="$(whoami)";
        ug="$(groups | awk '{print $1}')";
        sudo chown "$user":"$ug" "$MOUNT_DIR/ext"
        ;;
    "phone")
        sudo jmtpfs -o allow_other "$MOUNT_DIR/phone" 2>/dev/null
        ;;
    "tmp")
        checking_drives
        sudo mount -t vfat "/dev/sdb1" "$MOUNT_DIR/tmp" -o rw,umask=0000
        ;;
    *)
        echo "Wrong argument."
        exit 1
        ;;
esac

echo "Device mounted."
