#!/usr/bin/env bash

# shellcheck disable=SC1091

source config

if ping -c 1 google.com &> /dev/null; then
    echoGreen "Can ping sites."
else
    echoRed "Can't ping sites."
fi

if ping -c 1 1.1.1.1 &> /dev/null; then
    echoGreen "Can ping IP addresses on the internet."
else
    echoRed "Can't ping IP addresses on the internet."
fi
