#!/usr/bin/env bash

# shellcheck disable=SC1091

source config

if ping -c 1 192.168.1.1 &> /dev/null; then
    echoGreen "Connection check (1/3). Connection to the router exists."
else
    echoRed "Connection check (1/3). Connection to the router doesn't exist."
fi

if ping -c 1 google.com &> /dev/null; then
    echoGreen "Connection check (2/3). Can ping sites."
else
    echoRed "Connection check (2/3). Can't ping sites."
fi

if ping -c 1 1.1.1.1 &> /dev/null; then
    echoGreen "Connection check (3/3). Can ping IP addresses on the internet."
else
    echoRed "Connection check (3/3). Can't ping IP addresses on the internet."
fi
