#!/usr/bin/env bash

onescreen() {
	xrandr --output "$1" --auto --scale 1.0x1.0 $(echo "$allposs" | grep -v "\b$1" | awk '{print "--output", $1, "--off"}' | paste -sd ' ' -)
}

# Get all possible displays
allposs=$(xrandr -q | grep "connected")

onescreen "HDMI1"
