#!/usr/bin/env bash

# shellcheck disable=SC1091

source config
isinstalled jmtpfs fusermount veracrypt-console-bin || exit

phone="$HOME/mnt/phone"
backup4phoneDir="$phone/Internal shared storage/backup4phone"
backup4boxDir="$phone/Internal shared storage/backup4box"
localVCBackupFile="$HOME/.local/veracrypt/backup"
mntVCBackupDir="$HOME/mnt/vc-backup"

backup4phone() {
    [ ! -d "$backup4phoneDir" ] && echoRedExit "$backup4phoneDir doesn't exist!"
    if [ -d "$backup4phoneDir" ]; then
        echoBlue "Removing old backup."
        rm -vrf "${backup4phoneDir:?}"/*

        echoBlue -n "Copying files to the phone."
        # cp -n option is not used because I want it to overwrite all files
        cp -vR "$XDG_DOCUMENTS_DIR/keepass" "$backup4phoneDir" || notify-send "$0" "$XDG_DOCUMENTS_DIR/keepass doesn't exist."
    fi
}

backup4box() {
    [ ! -d "$backup4boxDir" ] && echoRedExit "$backup4boxDir doesn't exist!"

    if [ ! -f "$mntVCBackupDir/donotdelete" ]; then
        echoBlue "Mounting backup VeraCrypt volume."
        sudo veracrypt --pim=0 -k "" --protect-hidden=no "$localVCBackupFile" "$mntVCBackupDir"
    fi

    [ ! -d "$mntVCBackupDir/phone" ] && echoRedExit "$mntVCBackupDir/phone doesn't exist!"
    if [ -d "$mntVCBackupDir/phone" ]; then
        echoBlue "Copying backup from the phone to the VC volume."
        # cp -n option is not used because I want it to overwrite all files
        cp -vR "${backup4boxDir:?}"/* "$mntVCBackupDir/phone"
    fi

}

usage() {
    echo -e "Options: \n--mount or -m \n--umount or -u \n--backup4phone \n--backup4box \n--help or --usage"
    exit 1
}

case "$1" in
    "--mount" | "-m")
        sudo jmtpfs -o allow_other "$phone" 2>/dev/null
        exit 1 ;;
    "--umount" | '-u') 
        sudo fusermount -u "$phone"
        exit 1 ;;
    "--backup4phone") backup4phone ;;
    "--backup4box") backup4box ;;
    "--help" | "--usage") usage ;;
    *) usage ;;
esac
