#!/usr/bin/env bash

# shellcheck disable=SC1091

source config
isinstalled jmtpfs fusermount veracrypt-console-bin || exit

phone="$HOME/mnt/phone"
backupToPhoneDir="$phone/Internal storage/backup-from-pc"
backupToPCDir="$phone/Internal storage/backup-to-pc"
mntVCBackupDir="$HOME/mnt/vc-backup"

usage() {
    echo -e "Options: \nmount or m \numount or u \nbackup-to-phone \nbackup-to-pc"
    exit 1
}

backup-to-phone() {
    [ ! -d "$backupToPhoneDir" ] && echoRedExit "$backupToPhoneDir doesn't exist!"

    if [ -d "$backupToPhoneDir" ]; then
        now=$(date "+%d %B %Y [%A] %H:%M")
        echo "$now => phone" >> "$HOME/doc/last-backup-device.txt"

        echoBlue "Removing old backup from phone directory."
        rm -vrf "${backupToPhoneDir:?}"/*

        echoBlue -n "Copying files to the phone."
        # cp -n option is not used because I want it to overwrite all files
        cp -vR "$XDG_DOCUMENTS_DIR/keepass" "$backupToPhoneDir"
        # cp -vR "$XDG_DOCUMENTS_DIR/bookmarks.md" "$backupToPhoneDir"
        cp -vR "$XDG_DOCUMENTS_DIR/work" "$backupToPhoneDir"
        cp -vR "$XDG_DOCUMENTS_DIR/health" "$backupToPhoneDir"
    fi
}

backup-to-pc() {
    echoBlue "This option will overwrite everything from $mntVCBackupDir/phone directory. Do you want to proceed? [Y/n]"
    read -r answer

    if [ "$answer" != "y" ]; then
        echoRedExit "Exiting script."
    fi

    [ ! -d "$backupToPCDir" ] && echoRedExit "$backupToPCDir doesn't exist!"

    if [ ! -f "$mntVCBackupDir/donotdelete" ]; then
        echoBlue "Mounting backup VeraCrypt volume."
        sudo veracrypt --pim=0 -k "" --protect-hidden=no "$VC_BACKUP" "$mntVCBackupDir"
    fi

    [ ! -f "$mntVCBackupDir/donotdelete" ] && echoRedExit "Mounting failed."

    [ ! -d "$mntVCBackupDir/phone" ] && echoRedExit "$mntVCBackupDir/phone doesn't exist!"

    echoBlue "Copying backup from the phone to the VC volume."
    # cp -n option is not used because I want it to overwrite all files
    cp -vR "${backupToPCDir:?}"/* "$mntVCBackupDir/phone"
}

case "$1" in
    "mount" | "m")
        sudo jmtpfs -o allow_other "$phone" 2>/dev/null
        exit 1 ;;
    "umount" | 'u')
        sudo fusermount -u "$phone"
        exit 1 ;;
    "backup-to-phone") backup-to-phone ;;
    "backup-to-pc") backup-to-pc ;;
    *) usage ;;
esac
