#!/usr/bin/env bash

locationDir="$HOME/.local/git"
# locationDir="$HOME/.local/src"

usage() {
    echo -e "dmenu/dwm/dwmblocks-async/st/nsxiv"
    exit 1
}

case "$1" in
    "dmenu") 
        cd "$locationDir/dmenu-enhanced" || exit 1
        sudo make clean install ;;

    "dwm") 
        # echo "my dwm has built in refresh patch" ;;
        cd "$locationDir/dwm" || exit 1
        sudo make install || exit 1
        kill -HUP "$(pgrep -u "$USER" "\bdwm$")" ;;

    "dwmblocks-async") 
        echo "rebuilding dwmblocks-async..."
        cd "$locationDir/dwmblocks-async" || exit 1

        echo -n "type y to make file -> "
        read -r answer
        if [ "$answer" == "y" ]; then
            sudo make install || exit 1
        fi

        if [ "$(pgrep -u "$USER" "\bdwmblocks$")" ]; then
            kill -HUP "$(pgrep -u "$USER" "\bdwmblocks$")"
        fi

        dwmblocks & ;;

    "st")
        cd "$locationDir/st-enhanced" || exit 1
        sudo make install ;;

    "nsxiv") 
        cd "$locationDir/nsxiv" || exit 1
        rm -f config.h
        sudo make install ;;

    *) usage ;;
esac
