#!/usr/bin/env bash

# shellcheck disable=SC1091

source config
isinstalled setxkbmap xset xinput xmodmap || exit

touchpad="ELAN0501:01 04F3:3060 Touchpad"

setxkbmap
setxkbmap -option caps:escape
xset r rate 320 70
xmodmap -e 'keycode 135 = Super_R'

# Touchpad
xinput --set-prop "$touchpad" "libinput Tapping Enabled" "1"
xinput --set-prop "$touchpad" "libinput Natural Scrolling Enabled" "1"

# Mouse
xinput --set-prop "Kingsis Corporation ZOWIE Gaming mouse" "libinput Accel Speed" "-1" # zowie
# xinput --set-prop "2.4G Wireless Optical Mouse  Mouse" "libinput Accel Speed" "-1" # defender
# xinput --set-prop "Logitech Wireless Mouse" "libinput Accel Speed" "-1" # logitech (old one)

case "$1" in
    "us")
        setxkbmap us
        xmodmap -e 'clear mod1'
        xmodmap -e 'add mod1 = Alt_L'
        xmodmap -e 'add mod4 = Alt_R'
        notify-send "Switched to US keyboard."
        ;;
    "pl")
        setxkbmap pl
        notify-send "Switched to POLISH keyboard."
        ;;
    *)
        echo "Invalid argument. Usage: $0 [us|pl]"
        exit 1
        ;;
esac
