#!/usr/bin/env bash

isinstalled termdown || exit

volume_lvl="50"
song="$HOME/doc/sounds/ringtone.mp3"

[ "$(pamixer --get-mute)" = true ] && echo "Volume is muted!" && exit
# [ "$(bluetoothctl info | head -n 1)" != "Missing device address argument" ] && echo "headphones detected!" && exit

if [ "$(bluetoothctl info | head -n 1)" != "Missing device address argument" ]; then
    echo -n "Headphones detected. Do you want to start timer anyway? [y/N] "
    read -r answer

    if [ "$answer" != "y" ]; then
        exit
    fi
fi

termdown "$1" && mpv --volume="$volume_lvl" "$song"
