#!/usr/bin/env bash

# Use aunpack instead.

case "$1" in
    *.zip) unzip "$1" ;;
    *.tar.gz) tar -xzf "$1" ;;
    *.tar.bz2) tar -xjf "$1" ;;
    *.tar) tar -xf "$1" ;;
    *) echo "Unsupported format." ;;
esac
