#!/usr/bin/env bash

paru -Sc

[ ! -d "$HOME/tmp" ] && mkdir "$HOME/tmp"
cp -R "$XDG_CACHE_HOME/keepassxc" "$HOME/tmp/keepassxc"
cp "$XDG_CACHE_HOME/zsh_history" "$HOME/tmp/zsh_history"

rm -rf "$XDG_CONFIG_HOME/zsh/.zcompcache"
rm -rf "$XDG_CONFIG_HOME/zsh/.zcompdump"*

if ! rm -rf "${XDG_CACHE_HOME:?}/"*; then
  echo "Error: failed to remove cache directory contents" >&2
  rm -rf "$HOME/tmp/keepassxc"
  rm -rf "$HOME/tmp/zsh"
  exit 1
fi

mv "$HOME/tmp/keepassxc" "$XDG_CACHE_HOME"
mv "$HOME/tmp/zsh_history" "$XDG_CACHE_HOME"
