#!/bin/env bash

date

echo -e "\n--------------------"
echo "Uptime:"
uptime

echo -e "\n--------------------"
echo "Currently connected:"
w

echo -e "\n--------------------"
echo "Last logins:"
last -a | head -3

echo -e "\n--------------------"
echo "Utilization and most expensive processes:"
top -b | head -3
echo
top -b | head -10 | tail -4

echo -e "\n--------------------"
echo "Open TCP ports:"
nmap -p -T4 127.0.0.1

echo -e "\n--------------------"
echo "Current connections:"
ss -s

echo -e "\n--------------------"
echo "vmstat:"
vmstat 1 5
