#!/usr/bin/env bash

if [ -z "$1" ]; then
  echo "Usage: $0 <db_name>"
  exit 1
fi

dbName="$1"

mysqlUser="prospero"
mysqlHost="localhost"

sudo mysql -e "create database $dbName;" || exit 1
sudo mysql -e "grant all privileges on $dbName.* to '$mysqlUser'@'$mysqlHost';" || exit 1
