#!/usr/bin/env bash

if [ -z "$1" ]; then
  echo "Usage: $0 <db_name>"
  exit 1
fi

dbName="$1"

mariadbUser="prospero"
mariadbHost="localhost"

sudo mariadb -e "create database $dbName;" || exit 1
sudo mariadb -e "grant all privileges on $dbName.* to '$mariadbUser'@'$mariadbHost';" || exit 1
