#!/usr/bin/env bash

source config

activate71(){
    if [[ -f "$DEV_SCRIPTS_DIR/php" ]]; then
        rm "$DEV_SCRIPTS_DIR/php"
        rm "$DEV_SCRIPTS_DIR/phpize"

        ln -s "/usr/bin/php71" "$DEV_SCRIPTS_DIR/php"
        ln -s "/usr/bin/phpize71" "$DEV_SCRIPTS_DIR/phpize"

        echo "PHP 7.1 version activated."
    else
        echo "$DEV_SCRIPTS_DIR/php or $DEV_SCRIPTS_DIR/phpize don't exist."
    fi
}

activateLatest(){
    if [[ -f "$DEV_SCRIPTS_DIR/php" ]]; then
        rm "$DEV_SCRIPTS_DIR/php"
        rm "$DEV_SCRIPTS_DIR/phpize"

        ln -s "/usr/bin/php" "$DEV_SCRIPTS_DIR/php"
        ln -s "/usr/bin/phpize" "$DEV_SCRIPTS_DIR/phpize"

        echo "Latest PHP version activated."
    else
        echo "$DEV_SCRIPTS_DIR/php or $DEV_SCRIPTS_DIR/phpize don't exist."
    fi
}

case "$1" in
    "71") activate71 ;;
    "latest") activateLatest ;;
    *) exit 1 ;;
esac
