#!/usr/bin/env bash

activate74(){
    ln -s "/usr/bin/php74" "$SCRIPTS_DIR/php"
    ln -s "/usr/bin/phpize74" "$SCRIPTS_DIR/phpize"

    echo "PHP 7.4 version activated."
}

activateLatest(){
    ln -s "/usr/bin/php" "$SCRIPTS_DIR/php"
    ln -s "/usr/bin/phpize" "$SCRIPTS_DIR/phpize"

    echo "Latest PHP version activated."
}

main(){
    if [[ -f "$SCRIPTS_DIR/php" ]]; then
        rm "$SCRIPTS_DIR/php"
        rm "$SCRIPTS_DIR/phpize"

        case "$1" in
            "74") activate74 ;;
            "latest") activateLatest ;;
            *) exit 1 ;;
        esac
    else
        echo "$SCRIPTS_DIR/php or $SCRIPTS_DIR/phpize don't exist."
    fi
}

main "$1"
