#!/usr/bin/env bash

activate74(){
    ln -s "/usr/bin/php74" "$DEV_SCRIPTS_DIR/php"
    ln -s "/usr/bin/phpize74" "$DEV_SCRIPTS_DIR/phpize"

    echo "PHP 7.4 version activated."
}

activateLatest(){
    ln -s "/usr/bin/php" "$DEV_SCRIPTS_DIR/php"
    ln -s "/usr/bin/phpize" "$DEV_SCRIPTS_DIR/phpize"

    echo "Latest PHP version activated."
}

main(){
    if [[ -f "$DEV_SCRIPTS_DIR/php" ]]; then
        rm "$DEV_SCRIPTS_DIR/php"
        rm "$DEV_SCRIPTS_DIR/phpize"

        case "$1" in
            "74") activate74 ;;
            "latest") activateLatest ;;
            *) exit 1 ;;
        esac
    else
        echo "$DEV_SCRIPTS_DIR/php or $DEV_SCRIPTS_DIR/phpize don't exist."
    fi
}

main "$1"
