#!/usr/bin/env bash

source config

activate74(){
    if [[ -f "$DEV_SCRIPTS_DIR/php" ]]; then
        sudo rm "$DEV_SCRIPTS_DIR/php"
        sudo rm "$DEV_SCRIPTS_DIR/phpize"

        sudo ln -sf "/usr/bin/php74" "$DEV_SCRIPTS_DIR/php"
        sudo ln -sf "/usr/bin/phpize74" "$DEV_SCRIPTS_DIR/phpize"

        echo "PHP 7.4 version activated."
    else
        echo "$DEV_SCRIPTS_DIR/php or $DEV_SCRIPTS_DIR/phpize don't exist."
    fi
}

activateLatest(){
    if [[ -f "$DEV_SCRIPTS_DIR/php" ]]; then
        sudo rm "$DEV_SCRIPTS_DIR/php"
        sudo rm "$DEV_SCRIPTS_DIR/phpize"

        sudo ln -sf "/usr/bin/php" "$DEV_SCRIPTS_DIR/php"
        sudo ln -sf "/usr/bin/phpize" "$DEV_SCRIPTS_DIR/phpize"

        echo "Latest PHP version activated."
    else
        echo "$DEV_SCRIPTS_DIR/php or $DEV_SCRIPTS_DIR/phpize don't exist."
    fi
}

case "$1" in
    "74") activate74 ;;
    "latest") activateLatest ;;
    *) exit 1 ;;
esac
