#!/usr/bin/env bash

gitDir="$HOME/.local/git/acerice"
workTree="$HOME/"

cd "$HOME" || exit 1

git --git-dir="$gitDir" --work-tree="$workTree" add "$HOME/.zprofile"
git --git-dir="$gitDir" --work-tree="$workTree" add "$HOME/.gitignore"
git --git-dir="$gitDir" --work-tree="$workTree" add "$HOME/img/background"
git --git-dir="$gitDir" --work-tree="$workTree" add "$XDG_CONFIG_HOME/alacritty"
git --git-dir="$gitDir" --work-tree="$workTree" add "$XDG_CONFIG_HOME/awesome"
git --git-dir="$gitDir" --work-tree="$workTree" add "$XDG_CONFIG_HOME/browser-extensions"
git --git-dir="$gitDir" --work-tree="$workTree" add "$XDG_CONFIG_HOME/dunst"
git --git-dir="$gitDir" --work-tree="$workTree" add "$XDG_CONFIG_HOME/git"
git --git-dir="$gitDir" --work-tree="$workTree" add "$XDG_CONFIG_HOME/gtk-2.0"
git --git-dir="$gitDir" --work-tree="$workTree" add "$XDG_CONFIG_HOME/gtk-3.0"
git --git-dir="$gitDir" --work-tree="$workTree" add "$XDG_CONFIG_HOME/fontconfig"
git --git-dir="$gitDir" --work-tree="$workTree" add "$XDG_CONFIG_HOME/htop"
git --git-dir="$gitDir" --work-tree="$workTree" add "$XDG_CONFIG_HOME/i3"
git --git-dir="$gitDir" --work-tree="$workTree" add "$XDG_CONFIG_HOME/i3blocks"
git --git-dir="$gitDir" --work-tree="$workTree" add "$XDG_CONFIG_HOME/i3status"
git --git-dir="$gitDir" --work-tree="$workTree" add "$XDG_CONFIG_HOME/keepassxc"
git --git-dir="$gitDir" --work-tree="$workTree" add "$XDG_CONFIG_HOME/keepmenu"
git --git-dir="$gitDir" --work-tree="$workTree" add "$XDG_CONFIG_HOME/lazygit"
git --git-dir="$gitDir" --work-tree="$workTree" add "$XDG_CONFIG_HOME/lf"
git --git-dir="$gitDir" --work-tree="$workTree" add "$XDG_CONFIG_HOME/mpd"
git --git-dir="$gitDir" --work-tree="$workTree" add "$XDG_CONFIG_HOME/mpv"
git --git-dir="$gitDir" --work-tree="$workTree" add "$XDG_CONFIG_HOME/ncmpcpp"
git --git-dir="$gitDir" --work-tree="$workTree" add "$XDG_CONFIG_HOME/networkmanager-dmenu"
git --git-dir="$gitDir" --work-tree="$workTree" add "$XDG_CONFIG_HOME/nsxiv"
git --git-dir="$gitDir" --work-tree="$workTree" add "$XDG_CONFIG_HOME/qt5ct"
git --git-dir="$gitDir" --work-tree="$workTree" add "$XDG_CONFIG_HOME/tmux"
git --git-dir="$gitDir" --work-tree="$workTree" add "$XDG_CONFIG_HOME/wget"
git --git-dir="$gitDir" --work-tree="$workTree" add "$XDG_CONFIG_HOME/x11"
git --git-dir="$gitDir" --work-tree="$workTree" add "$XDG_CONFIG_HOME/zathura"
git --git-dir="$gitDir" --work-tree="$workTree" add "$XDG_CONFIG_HOME/zsh"
git --git-dir="$gitDir" --work-tree="$workTree" add "$XDG_CONFIG_HOME/backup.cfg"
git --git-dir="$gitDir" --work-tree="$workTree" add "$XDG_CONFIG_HOME/user-dirs.dirs"
git --git-dir="$gitDir" --work-tree="$workTree" add "$XDG_CONFIG_HOME/user-dirs.locale"
git --git-dir="$gitDir" --work-tree="$workTree" add "$XDG_CONFIG_HOME/QtProject.conf"
git --git-dir="$gitDir" --work-tree="$workTree" add -u

git --git-dir="$gitDir" --work-tree="$workTree" commit -m 'sync'
git --git-dir="$gitDir" --work-tree="$workTree" push
