#!/usr/bin/env bash

gitDir="$HOME/.local/git/appgo"
workTree="$HOME/"

cd "$HOME" || exit 1

git --git-dir="$gitDir" --work-tree="$workTree" add "$HOME/.zprofile"
git --git-dir="$gitDir" --work-tree="$workTree" add "$HOME/.gitignore"
git --git-dir="$gitDir" --work-tree="$workTree" add "$HOME/.ssh"
git --git-dir="$gitDir" --work-tree="$workTree" add "$HOME/.gnupg"
git --git-dir="$gitDir" --work-tree="$workTree" add "$HOME/img/background"
git --git-dir="$gitDir" --work-tree="$workTree" add "$XDG_CONFIG_HOME/alacritty"
git --git-dir="$gitDir" --work-tree="$workTree" add "$XDG_CONFIG_HOME/dunst"
git --git-dir="$gitDir" --work-tree="$workTree" add "$XDG_CONFIG_HOME/git"
git --git-dir="$gitDir" --work-tree="$workTree" add "$XDG_CONFIG_HOME/gtk-2.0"
git --git-dir="$gitDir" --work-tree="$workTree" add "$XDG_CONFIG_HOME/gtk-3.0"
git --git-dir="$gitDir" --work-tree="$workTree" add "$XDG_CONFIG_HOME/i3"
git --git-dir="$gitDir" --work-tree="$workTree" add "$XDG_CONFIG_HOME/i3blocks"
git --git-dir="$gitDir" --work-tree="$workTree" add "$XDG_CONFIG_HOME/i3status"
git --git-dir="$gitDir" --work-tree="$workTree" add "$XDG_CONFIG_HOME/lazygit"
git --git-dir="$gitDir" --work-tree="$workTree" add "$XDG_CONFIG_HOME/lf"
git --git-dir="$gitDir" --work-tree="$workTree" add "$XDG_CONFIG_HOME/nsxiv"
git --git-dir="$gitDir" --work-tree="$workTree" add "$XDG_CONFIG_HOME/qt5ct"
git --git-dir="$gitDir" --work-tree="$workTree" add "$XDG_CONFIG_HOME/wget"
git --git-dir="$gitDir" --work-tree="$workTree" add "$XDG_CONFIG_HOME/x11"
git --git-dir="$gitDir" --work-tree="$workTree" add "$XDG_CONFIG_HOME/zathura"
git --git-dir="$gitDir" --work-tree="$workTree" add "$XDG_CONFIG_HOME/zsh"
git --git-dir="$gitDir" --work-tree="$workTree" add "$XDG_CONFIG_HOME/user-dirs.dirs"
git --git-dir="$gitDir" --work-tree="$workTree" add "$XDG_CONFIG_HOME/user-dirs.locale"
git --git-dir="$gitDir" --work-tree="$workTree" add -u

git --git-dir="$gitDir" --work-tree="$workTree" commit -m 'appgo'
git --git-dir="$gitDir" --work-tree="$workTree" push
