#!/usr/bin/env bash

# shellcheck disable=SC1091

source config
isinstalled veracrypt-console-bin file tar || exit

driveBackupFile="$HOME/mnt/dev/backup"
backuptestDir="$HOME/mnt/tmp"
tmpDir="$HOME/tmp"

main(){
    echoBlue "Mounting $driveBackupFile volume to $backuptestDir."
    [ -f "$backuptestDir/backup" ] && echoRedExit "Looks like something is already mounted in $backuptestDir."
    [ -f "$driveBackupFile" ] && sudo veracrypt -t --pim=0 -k "" --protect-hidden=no --display-password "$driveBackupFile" "$backuptestDir"
    [ ! -f "$driveBackupFile" ] && echoRedExit "$driveBackupFile doesn't exist."

    echoBlue -n "Running tests."
    ls --color=auto -alh "$backuptestDir"
    runDust "$backuptestDir" 2>/dev/null
    file "$backuptestDir/backup.tar.gz"
    file "$backuptestDir/oldbackup.tar.gz"
    file "$backuptestDir/img.tar.gz"

    echoBlue -n "Do you want to copy backup.tar.gz to $tmpDir? [y/N]"
    read -r answer

    if [ "$answer" == "y" ]; then
        echoBlue "Deleting old tar file and directory."
        [ -f "$tmpDir/backup.tar.gz" ] && rm -vrf "$tmpDir/backup.tar.gz"
        [ -d "$tmpDir/home" ] && rm -rf "${tmpDir/home:?}"

        echoBlue "Copying backup.tar.gz to $tmpDir for further tests."
        cp -v "$backuptestDir/backup.tar.gz" "$tmpDir"
        cd "$tmpDir" || exit 1

        echoBlue "Untaring backup file."
        tar zxf "$tmpDir/backup.tar.gz"

        echoBlue "Check $tmpDir/home directory."
        ls --color=auto -alh "$tmpDir"
        echo
    fi

    echoBlue "Unmounting $driveBackupFile volume."
    sudo veracrypt -d "$backuptestDir"
    [ -f "$backuptestDir/backup" ] && echoRed "Looks like unmounting failed. Do it manually."
}

main
