#!/usr/bin/env bash

[ ! -d "$XDG_CONFIG_HOME/etc" ] && mkdir -p "$XDG_CONFIG_HOME/etc"

[ -d "$XDG_CONFIG_HOME/etc/httpd" ] && rm -rf "$XDG_CONFIG_HOME/etc/httpd/"
sudo cp -R /etc/httpd "$XDG_CONFIG_HOME/etc/httpd"
sudo chown prospero:prospero -R "$XDG_CONFIG_HOME/etc/httpd"

[ -d "$XDG_CONFIG_HOME/etc/php" ] && rm -rf "$XDG_CONFIG_HOME/etc/php/"
sudo cp -R /etc/php "$XDG_CONFIG_HOME/etc/php"
sudo chown prospero:prospero -R "$XDG_CONFIG_HOME/etc/php"
