#!/usr/bin/env bash

# shellcheck disable=SC1091

source config
isinstalled veracrypt-console-bin mountpoint || exit

set -e

mntVCBackupDir="$HOME/mnt/vc-backup"

main() {
    echo -n "Run backupupdate? [y/N] "
    read -r answer

    if [ "$answer" == "y" ]; then
        backupupdate standard || exit
    fi

    mountedDevice="$HOME/mnt/$1"

    [ ! -f "$VC_BACKUP" ] && echoRedExit "$VC_BACKUP does not exist."
    [ ! -f "$mountedDevice/backup" ] && echoRedExit "$mountedDevice is probably not mounted."

    if mountpoint -q "$mntVCBackupDir"; then
        echoBlue "Unmounting VeraCrypt volume."
        sudo veracrypt -d "$mntVCBackupDir"

        mountpoint -q "$mntVCBackupDir" && echoRedExit "Error: $mntVCBackupDir is still mounted."
    fi

    echoBlue "Replacing old backup file."
    mv -v "$mountedDevice/backup" "$mountedDevice/backup-old"

    echoBlue -n "Copying current backup file to $mountedDevice."
    cp -v "$VC_BACKUP" "$mountedDevice"

    echoBlue -n "Info:"
    runDust "$mountedDevice"
    ls --color=auto -alh "$mountedDevice"

    now=$(date "+%d %B %Y [%A] %H:%M")
    echo "$now => $1" >> "$HOME/doc/last-backup-device.txt"

    echoBlue -n "Run backuptest? [y/N]"
    read -r answer

    if [ "$answer" == "y" ]; then
        backuptest
    fi
}

case "$1" in
    "usb1")
        main "usb1" ;;
    "usb2")
        main "usb2" ;;
    "ext")
        main "ext" ;;
    "last")
        cat "$HOME/doc/last-backup-device.txt" ;;
    *)
        echo "usage: usb1/usb2/ext/last";
esac
