#!/usr/bin/env bash

source config
isinstalled tar || exit

backupConfig="$XDG_CONFIG_HOME/backup.cfg"
[ ! -f "$backupConfig" ] && echoRedExit "$backupConfig file doesn't exist"

usage() {
    echo -e "Options: \n- standard or s \n- img"
    exit 1
}

standardBackup() {
    [ ! -f "$VC_BACKUP_MNT_DIR/backup.tar.gz" ] && echoRedExit "$VC_BACKUP_MNT_DIR/backup.tar.gz doesn't exist!"

    echoBlue "Replacing oldbackup.tar.gz file."
    mv -v "$VC_BACKUP_MNT_DIR/backup.tar.gz" "$VC_BACKUP_MNT_DIR/oldbackup.tar.gz"

    echoBlue -n "Creating new backup tar archive."
    tar -czf "$VC_BACKUP_MNT_DIR/backup.tar.gz" -T "$backupConfig" || echoRedExit "tar command failed"

    echoBlue -n "Backup info:"
    runDust "$VC_BACKUP_MNT_DIR"
    runDust "$VC_BACKUP_MNT_DIR/backup.tar.gz"
    runDust "$VC_BACKUP_MNT_DIR/oldbackup.tar.gz"
    file "$VC_BACKUP_MNT_DIR/backup.tar.gz" "$VC_BACKUP_MNT_DIR/oldbackup.tar.gz"

    echoBlue -n "$HOME/doc:"
    runDust "$HOME/doc"
}

imgBackup() {
    echoBlue "Before update info:"
    runDust "$VC_BACKUP_MNT_DIR/img.tar.gz"

    echoBlue -n "Deleting and creating new img tar archive."
    rm -rf "$VC_BACKUP_MNT_DIR/img.tar.gz"
    tar -zcf "$VC_BACKUP_MNT_DIR/img.tar.gz" "$HOME/img"

    echoBlue -n "After update:"
    runDust "$VC_BACKUP_MNT_DIR"
    runDust "$VC_BACKUP_MNT_DIR/img.tar.gz"

    echoBlue -n "Info about updated file:"
    file "$VC_BACKUP_MNT_DIR/img.tar.gz"
}

case "$1" in
  "standard" | "s" )
      backupmnt
      standardBackup ;;
  "img") 
      backupmnt
      imgBackup ;;
  *) usage ;;
esac
