#!/usr/bin/env bash

# shellcheck disable=SC1091
# shellcheck disable=SC2115

source config
isinstalled veracrypt-console-bin file tar || exit

backuptestDir="$HOME/mnt/tmp"
tmpDir="$HOME/tmp"

main(){
    [ ! -d "$backuptestDir" ] && mkdir -p "$backuptestDir"

    echoBlue -n "Mounting $driveBackupFile volume to $backuptestDir."
    [ -f "$backuptestDir/backup" ] && echoRedExit "[!] Looks like something is already mounted in $backuptestDir."
    [ -f "$driveBackupFile" ] && sudo veracrypt -t --pim=0 -k "" --protect-hidden=no --display-password "$driveBackupFile" "$backuptestDir"
    [ ! -f "$driveBackupFile" ] && echoRedExit "[!] $driveBackupFile doesn't exist."

    echoBlue -n "Running tests."
    ls --color=auto -alh "$backuptestDir"
    runDust "$backuptestDir" 2>/dev/null
    file "$backuptestDir/backup.tar.gz"
    file "$backuptestDir/oldbackup.tar.gz"
    file "$backuptestDir/img.tar.gz"

    echoBlue -n "Do you want to copy backup.tar.gz to $tmpDir? [y/N]"
    read -rp "Answer: " answer

    if [ "$answer" == "y" ]; then
        echoYellow "=> Deleting old tar file and directory..."
        [ -f "$tmpDir/backup.tar.gz" ] && rm -vrf "$tmpDir/backup.tar.gz"
        [ -d "$tmpDir/home" ] && rm -rf "$tmpDir/home"

        echoYellow "=> Copying backup.tar.gz to $tmpDir for further tests..."
        cp -v "$backuptestDir/backup.tar.gz" "$tmpDir"

        echoYellow "=> Untaring backup file..."
        tar zxf "$tmpDir/backup.tar.gz" -C "$tmpDir"

        echoBlue -n "Check $tmpDir/home directory."
        ls --color=auto -alh "$tmpDir"
        echo
    fi

    echoYellow "Unmounting $driveBackupFile volume..."
    sudo veracrypt -d "$backuptestDir"
    [ -f "$backuptestDir/backup" ] && echoRed "[!] Looks like unmounting failed. Do it manually."
}

echoBlue "Which dir in $HOME/mnt? [usb/usb2/ext]"
read -rp "Enter your choice: " answer

if [[ "$answer" != "usb" && "$answer" != "usb2" && "$answer" != "ext" ]]; then
    echoRedExit "[!] Only usb/usb2/ext allowed."
fi

driveBackupFile="$HOME/mnt/$answer/backup"

main
