#!/usr/bin/env bash

# shellcheck disable=SC1091

source config
isinstalled veracrypt-console-bin mountpoint || exit

set -e

mntVCBackupDir="$HOME/mnt/vc-backup"
backupLocalVolume="$HOME/.local/veracrypt/backup"

main() {
    mountedDevice="$HOME/mnt/$1"

    echo "$1" > "$HOME/doc/last-backup-device.txt"

    [ ! -f "$backupLocalVolume" ] && echoRedExit "$backupLocalVolume does not exist."
    [ ! -f "$mountedDevice/backup" ] && echoRedExit "$mountedDevice is probably not mounted."

    if mountpoint -q "$mntVCBackupDir"; then
        echoBlue "Unmounting VeraCrypt volume."
        sudo veracrypt -d "$mntVCBackupDir"

        mountpoint -q "$mntVCBackupDir" && echoRedExit "Error: $mntVCBackupDir is still mounted."
    fi

    echoBlue "Replacing old backup file."
    mv -v "$mountedDevice/backup" "$mountedDevice/backup-old"

    echoBlue -n "Copying current backup file to $mountedDevice."
    cp -v "$backupLocalVolume" "$mountedDevice"

    echoBlue -n "Info:"
    runDust "$mountedDevice"
    ls --color=auto -alh "$mountedDevice"

    echoBlue -n "Run backuptest? [y/N]"
    read -r answer

    if [ "$answer" == "y" ]; then
        backuptest
    fi
}

case "$1" in
    "usb1")
        main "usb1" ;;
    "usb2")
        main "usb2" ;;
    "last")
        cat "$HOME/doc/last-backup-device.txt" ;;
    *)
        echo "usage: usb1/usb2/last";
esac
