#!/usr/bin/env bash

source _scripts_config
isinstalled tar cronie dust || exit

BACKUP_CONFIG="$XDG_CONFIG_HOME/backup.cfg"
MNT_DIR="$HOME/mnt/dev"

[ -z "$1" ] && echoRedExit "No argument."
drive="$1"

[ -f "$BACKUP_CONFIG" ] || echoRedExit "$BACKUP_CONFIG file doesn't exist"

if [ -f "$MNT_DIR/backup.tar.gz" ]; then
    echo "=> Replacing oldbackup.tar.gz file."
    mv -v "$MNT_DIR/backup.tar.gz" "$MNT_DIR/oldbackup.tar.gz"
fi

echo "=> Creating new backup tar archives."
crontab -l > "$HOME/doc/crontab.txt"
tar -czf "$MNT_DIR/backup.tar.gz" -T "$BACKUP_CONFIG" || echoRedExit "tar command failed"
tar -czf "$MNT_DIR/img.tar.gz" "$HOME/img" || echoRedExit "tar command failed"

echo -e "\n=> Backup info:"
dust -br -d 0 --print-errors "$MNT_DIR"
ls --color=auto -alh --group-directories-first "$MNT_DIR"

echo -e "\n=> $HOME/doc:"
dust -br -d 0 "$HOME/doc"

now=$(date "+%d %B %Y [%A] %H:%M")
echo "luks: $now => $drive" >> "$HOME/doc/last-backup-device.txt"
