#!/usr/bin/env bash

# shellcheck disable=SC1091
# shellcheck disable=SC2115

source _scripts_config
isinstalled veracrypt-console-bin file tar || exit

vc_tmp_mount_dir="$HOME/mnt/tmp"
drive_backup_file="$HOME/mnt/dev/backup"

[ ! -d "$vc_tmp_mount_dir" ] && mkdir -p "$vc_tmp_mount_dir"

echoBlue "Mounting $drive_backup_file volume to $vc_tmp_mount_dir."
[ -f "$vc_tmp_mount_dir/backup" ] && echoRedExit "[!] Looks like something is already mounted in $vc_tmp_mount_dir."

[ ! -f "$drive_backup_file" ] && echoRedExit "[!] $drive_backup_file doesn't exist."
[ -f "$drive_backup_file" ] && sudo veracrypt -t --pim=0 -k "" --protect-hidden=no --display-password "$drive_backup_file" "$vc_tmp_mount_dir"

echoBlue "Tests:"
runDust "$vc_tmp_mount_dir" 2>/dev/null
file "$vc_tmp_mount_dir/backup.tar.gz"
file "$vc_tmp_mount_dir/oldbackup.tar.gz"
file "$vc_tmp_mount_dir/img.tar.gz"
ls --color=auto -al --group-directories-first -h "$vc_tmp_mount_dir"

echoBlue -n "Do you want to copy backup.tar.gz to $TMP_DIR? [y/N]"
read -rp "Answer: " answer

if [ "$answer" == "y" ]; then
    echoBlue "Deleting old tar file and directory..."
    [ -f "$TMP_DIR/backup.tar.gz" ] && rm -vrf "$TMP_DIR/backup.tar.gz"
    [ -d "$TMP_DIR/home" ] && rm -rf "$TMP_DIR/home"

    echoBlue "Copying backup.tar.gz to $TMP_DIR for further tests..."
    cp -v "$vc_tmp_mount_dir/backup.tar.gz" "$TMP_DIR"

    echoBlue "Untaring backup file..."
    tar zxf "$TMP_DIR/backup.tar.gz" -C "$TMP_DIR"

    echoGreen "Check $TMP_DIR/home directory."
    echo
fi

echoYellow "Unmounting $drive_backup_file volume..."
sudo veracrypt -d "$vc_tmp_mount_dir"
[ -f "$vc_tmp_mount_dir/backup" ] && echoRedExit "[!] Looks like unmounting failed. Do it manually."
echo -e "\nChecking if $vc_tmp_mount_dir is empty:"
ls --color=auto -alh "$vc_tmp_mount_dir"
