#!/usr/bin/env bash

# shellcheck disable=SC1091

source config
isinstalled veracrypt-console-bin mountpoint || exit

set -e

main() {
    echo -n "Run backup_create? [y/N] "
    read -r answer

    if [ "$answer" == "y" ]; then
        backup_create standard || exit
        echo -e "\nCreating new backup finished.\n"
        echo "========="
        echo
    fi

    mountedDevice="$HOME/mnt/dev"

    [ ! -f "$VC_BACKUP" ] && echoRedExit "$VC_BACKUP does not exist."
    [ ! -f "$mountedDevice/backup" ] && echoRedExit "$mountedDevice is probably not mounted."

    if mountpoint -q "$VC_BACKUP_MNT_DIR"; then
        echoBlue "Unmounting VeraCrypt volume."
        sudo veracrypt -d "$VC_BACKUP_MNT_DIR"

        mountpoint -q "$VC_BACKUP_MNT_DIR" && echoRedExit "Error: $VC_BACKUP_MNT_DIR is still mounted."
    fi

    echoBlue "Replacing old backup file."
    mv -v "$mountedDevice/backup" "$mountedDevice/backup-old"

    echoBlue -n "Copying current backup file to $mountedDevice."
    cp -v "$VC_BACKUP" "$mountedDevice"

    echoBlue -n "Info:"
    runDust "$mountedDevice"
    ls --color=auto -alh "$mountedDevice"

    now=$(date "+%d %B %Y [%A] %H:%M")
    echo "$now => $1" >> "$HOME/doc/last-backup-device.txt"
    exit

    echoBlue -n "Run backup_test? [y/N]"
    read -r answer

    if [ "$answer" == "y" ]; then
        backup_test
    fi
}

case "$1" in
    "make")
        if [ "$2" != "--note" ]; then
            echo "no note added"
            exit 1
        fi

        main "$3"
        ;;
    "last")
        cat "$HOME/doc/last-backup-device.txt" ;;
    *)
        echo "usage: make --note goodram/last";
esac
