#!/usr/bin/env bash

source _scripts_config
isinstalled tar cronie || exit

BACKUP_CONFIG="$XDG_CONFIG_HOME/backup.cfg"

backup_standard() {
    [ -f "$BACKUP_CONFIG" ] || echoRedExit "$BACKUP_CONFIG file doesn't exist"
    [ -f "$VC_BACKUP_MNT_DIR/backup.tar.gz" ] || echoRedExit "$VC_BACKUP_MNT_DIR/backup.tar.gz doesn't exist!"

    echoBlue "Replacing oldbackup.tar.gz file."
    mv -v "$VC_BACKUP_MNT_DIR/backup.tar.gz" "$VC_BACKUP_MNT_DIR/oldbackup.tar.gz"

    echoBlue -n "Creating new backup tar archive."
    crontab -l > "$HOME/doc/crontab.txt"
    tar -czf "$VC_BACKUP_MNT_DIR/backup.tar.gz" -T "$BACKUP_CONFIG" || echoRedExit "tar command failed"

    echoBlue -n "Backup info:"
    runDust "$VC_BACKUP_MNT_DIR"
    runDust "$VC_BACKUP_MNT_DIR/backup.tar.gz"
    runDust "$VC_BACKUP_MNT_DIR/oldbackup.tar.gz"
    file "$VC_BACKUP_MNT_DIR/backup.tar.gz" "$VC_BACKUP_MNT_DIR/oldbackup.tar.gz"
    ls --color=auto -alh --group-directories-first "$VC_BACKUP_MNT_DIR"

    echoBlue -n "$HOME/doc:"
    runDust "$HOME/doc"
}

backup_img() {
    echoBlue "Before update info:"
    runDust "$VC_BACKUP_MNT_DIR/img.tar.gz"

    echoBlue -n "Deleting and creating new img tar archive."
    rm -rf "$VC_BACKUP_MNT_DIR/img.tar.gz"
    tar -zcf "$VC_BACKUP_MNT_DIR/img.tar.gz" "$HOME/img"

    echoBlue -n "After update:"
    runDust "$VC_BACKUP_MNT_DIR"
    runDust "$VC_BACKUP_MNT_DIR/img.tar.gz"

    echoBlue -n "Info about updated file:"
    file "$VC_BACKUP_MNT_DIR/img.tar.gz"
}

case "${1-usage}" in
    "standard" | "s" )
        bmnt
        backup_standard
        ;;
    "img") 
        bmnt 
        backup_img
        ;;
    *)
        echo -e "Options: \n- standard or s \n- img"
        exit 1
        ;;
esac
