#!/usr/bin/env bash

syncDir() {
    local directory="$1"
    cd "$directory" || exit 1
    git add .
    git commit -m "sync"
    git push
}

pullDir() {
    local directory="$1"
    cd "$directory" || exit 1
    git pull
}

if [ "$1" == "push" ]; then
    syncDir "$HOME/.local/scripts"
    syncDir "$HOME/.local/synced-doc"
    syncDir "$HOME/.local/web"
    syncDir "$HOME/.config/nvim"
elif [ "$1" == "pull" ]; then
    pullDir "$HOME/.local/scripts"
    pullDir "$HOME/.local/synced-doc"
    pullDir "$HOME/.local/web"
    pullDir "$HOME/.config/nvim"
fi
