#!/usr/bin/env bash

# shellcheck disable=SC1091

source _scripts_config
# set -euo pipefail

declare -Ar GIT_DIRS=(
    ["scripts"]="$HOME/.local/scripts"
    # ["moonwm"]="$HOME/.local/git/projects/moonwm"
    ["st-enhanced"]="$HOME/.local/projects/git/st-enhanced"
    ["dmenu-enhanced"]="$HOME/.local/projects/git/dmenu-enhanced"
    ["work"]="$HOME/.local/projects/git/work"
    # ["multi"]="$HOME/.local/projects/git/multi"
    ["nvim"]="$HOME/.config/nvim"
    ["dotfiles"]="$HOME/.local/projects/git/dotfiles"
    # ["server-files"]="$HOME/.local/projects/git/server-files"
    ["adminer"]="/srv/http/adminer"
)

git_status() {
    local dir="$1"

    echo -n "Working dir: "
    echoGreen "$dir"
    cd "$dir" || exit 1
    git status -s
    echo
}

git_push() {
    local dir="$1"

    echo -n "Working dir: "
    echoGreen "$dir"
    cd "$dir" || exit 1
    git add -A

    # if git diff --cached --quiet; then
    #     echo "nothing to commit"
    # else
        git commit -m "sync"
    # fi

    git push
    echo
}

git_pull() {
    local dir="$1"

    echo -n "Working dir: "
    echoGreen "$dir"
    cd "$dir" || exit 1
    git pull
    echo
}

check_if_dir_exists() {
    if [ ! -d "$1" ]; then
        echoRed -n "$1 doesn't exist"
        return
    fi
}

case "${1-usage}" in
    "status")
        for key in "${!GIT_DIRS[@]}"; do
            dir="${GIT_DIRS[$key]}"
            check_if_dir_exists "$dir"
            git_status "$dir"
        done
        ;;
    "push")
        for key in "${!GIT_DIRS[@]}"; do
            dir="${GIT_DIRS[$key]}"
            check_if_dir_exists "$dir"
            git_push "$dir"
        done
        ;;
    "pull")
        for key in "${!GIT_DIRS[@]}"; do
            dir="${GIT_DIRS[$key]}"
            check_if_dir_exists "$dir"
            git_pull "$dir"
        done
        ;;
    "usage")
        echo "Usage: status/push/pull"
        exit 1
        ;;
esac
