#!/usr/bin/env bash

pgrep -f batcron > /dev/null || batcron &

# if [ "$HOST" = "moon" ]; then
if [ "$(hostname)" = "moon" ]; then
    pgrep -f memcron > /dev/null || memcron &
    pgrep -f netcron > /dev/null || netcron &
fi

exec i3
