#!/usr/bin/env bash

if [ "$(hostname)" = "moon" ]; then
    pgrep -f batcron > /dev/null || batcron &
    pgrep -f memcron > /dev/null || memcron &
    pgrep -f netcron > /dev/null || netcron &
fi

exec i3
