#!/usr/bin/env bash

# HOST="$(hostname)"

# if [ "$HOST" == "moon" ]; then
#     xrandr --output eDP1 --off --output HDMI1 --mode 1920x1080 --pos 0x0 --rotate normal --output VIRTUAL1 --off
# elif [ "$HOST" == "arch" ]; then
#     xrandr --output eDP1 --off --output DP1 --mode 1920x1080 --pos 0x0 --rotate normal --output HDMI1 --off --output HDMI2 --mode 1920x1080 --pos 1920x0 --rotate normal --output VIRTUAL1 --off
# else
#     notify-send "$0" "hostname isn't moon/arch"
# fi

hdmi=$(xrandr -q | grep "connected" | awk '/ connected/{print $1}' | grep HDMI)

if [ "$hdmi" ]; then
    xrandr --output eDP1 --off \
        --output DP1 --off \
        --output HDMI1 --off \
        --output "$hdmi" --primary --mode 1920x1080 --pos 0x0 --rotate normal \
        --output VIRTUAL1 --off

    notify-send "Switched to HDMI display."
    remaps us
fi
