#!/usr/bin/env bash

hdmi=$(xrandr -q | grep -w "connected" | grep "HDMI" | awk '/ connected/{print $1}')
edp=$(xrandr -q | grep -w "connected" | grep "eDP" | awk '/ connected/{print $1}')

if [ "$hdmi" ]; then
    xrandr --output $edp --off \
        --output $hdmi --primary --mode 1920x1080 --pos 1937x0 --rotate normal \
        --output DP-1 --off \
        --output DP-2 --off \
        --output DP-3 --off \
        --output DP-4 --off \
        --output DP-1-0 --off \
        --output DP-1-1 --off \
        --output HDMI-1-0 --off \
        --output DP-1-2 --off \
        --output DP-1-3 --off

    setbg "$HOME/img/background"
elif [ "$edp" ]; then
    xrandr --output $edp --mode 1920x1080 --rotate normal \
        --output HDMI-1 --off \
        --output HDMI-1-0 --off \
        --output DP-1 --off \
        --output DP-2 --off \
        --output DP-3 --off \
        --output DP-4 --off \
        --output DP-1-0 --off \
        --output DP-1-1 --off \
        --output DP-1-2 --off \
        --output DP-1-3 --off

    setbg "$HOME/img/background"
fi
