#!/usr/bin/env bash

# shellcheck disable=SC1091

source _scripts_config

# set -euo pipefail

isinstalled setxkbmap xset xinput xmodmap || exit

# xinput list
touchpad="ELAN0501:01 04F3:3060 Touchpad"
touchpad_thinkpad="SynPS/2 Synaptics TouchPad"

remap() {
    setxkbmap
    setxkbmap -option caps:escape
    xset r rate 320 70
    xmodmap -e 'keycode 135 = Super_R'

    # Touchpad
    xinput --set-prop "$touchpad" "libinput Tapping Enabled" "1"
    xinput --set-prop "$touchpad" "libinput Natural Scrolling Enabled" "1"
    xinput --set-prop "$touchpad_thinkpad" "libinput Natural Scrolling Enabled" "1"
    xinput --set-prop "$touchpad_thinkpad" "libinput Accel Speed" "0.5"

    # Mouse
    xinput --set-prop "Kingsis Corporation ZOWIE Gaming mouse" "libinput Accel Speed" "-1"
    xinput --set-prop "2.4G Wireless Optical Mouse  Mouse" "libinput Accel Speed" "-1"
    xinput --set-prop "pointer:Logitech USB Receiver Mouse" "libinput Accel Speed" "-0.9"
}

remaps_toggle() {
    if [ "$(setxkbmap -query | awk '/layout/ {print $2}')" == "us" ]; then
        notify-send "Switching to polish keyboard..."
        remap
        setxkbmap pl
    else
        notify-send "Switching to us keyboard..."
        remap
        setxkbmap us
        xmodmap -e 'clear mod1'
        xmodmap -e 'add mod1 = Alt_L'
        xmodmap -e 'add mod4 = Alt_R'
    fi
}

if [ $# -eq 0 ]; then
    remaps_toggle
    exit
else
    value="$1"
fi

case "$value" in
    "us")
        notify-send "Switching to us keyboard..."
        remap
        setxkbmap us
        xmodmap -e 'clear mod1'
        xmodmap -e 'add mod1 = Alt_L'
        xmodmap -e 'add mod4 = Alt_R'
        ;;
    "pl")
        notify-send "Switching to polish keyboard..."
        remap
        setxkbmap pl
        ;;
    *)
        echoRedExit "Wrong argument."
        ;;
esac
