#!/usr/bin/env bash

source _scripts_config
isinstalled termdown || exit

RINGTONE="$HOME/music/songs/Coldplay - Viva la Vida.mp3"
VOLUME_LVL="100"

if [ ! "$1" ]; then
    termdown
    exit
fi

if [ ! -f "$RINGTONE" ]; then
    echoRedExit "$RINGTONE not found."
fi

# [ "$(pamixer --get-mute)" = true ] && echo "Volume is muted!" && exit
# [ "$(bluetoothctl info | head -n 1)" != "Missing device address argument" ] && echo "headphones detected!" && exit

if [ "$(bluetoothctl info | head -n 1)" != "Missing device address argument" ]; then
    echo -n "Headphones detected. Do you want to start timer anyway? [y/N] "
    read -r answer

    if [ "$answer" != "y" ]; then
        exit
    fi
fi

termdown "$1" && mpv --volume="$VOLUME_LVL" "$RINGTONE"
