#!/usr/bin/env bash

usage="$(vnstat -i wlp3s0 --oneline | grep 'wlp3s0' | awk -F';' '{print $6}')"

# if (( $(bc <<< "$usage >= 2.90") )); then
#     echo hi
# fi

result=$(echo "$usage > 2.90" | bc -l)

echo $result
exit

if [[ "$result" -eq 1 ]]; then
    echo hi
fi

# if [ $(echo "$usage > 2.90" | bc -l) -eq 1 ]; then
#     echo "True"
# fi

# while true
# do
#     sleep 5m
# done
