#!/usr/bin/env bash

source config

memory=$(free --mebi | sed -n '2{p;q}' | awk '{printf ("📀%2.2fG/%2.2fG\n", ( $3 / 1024), ($2 / 1024))}')
echo $memory
exit

memory=$(free --mebi | sed -n '2{p;q}')
used_memory=$(echo "$memory" | awk '{print $3}')
formatted_used=$(bc <<< "scale=2; $used_memory / 1024")

if (( $(bc <<< "$formatted_used >= 3.7") )); then
    mpv --volume=70 "$NOTIFICATION_SOUNDS_DIR/cute-notification.mp3" 1>/dev/null
    notify-send -u critical "Low memory!" "${formatted_used}GiB is used by system."
    notify-send "Memory hungry processes" "$(ps axch -o cmd:15,%mem --sort=-%mem | head)"
fi
