#!/usr/bin/env bash

# usage="$(vnstat -i wlp3s0 --oneline | awk -F';' '{print $6}' | cut -d ' ' -f 1)"
# usage=$(vnstat -i wlp3s0 --oneline | awk -F';' '{split($6, a, " "); print a[1]}')

NET_USAGE_SOUND="$HOME/doc/sounds/net-usage.wav"
INTERFACE="wlp3s0"
THRESHOLD=3.00

if ! command -v vnstat &>/dev/null
then
    notify-send "netcron" "vnstat is not installed"
    exit 1
fi

if ! command -v bc &>/dev/null
then
    notify-send "netcron" "bc is not installed"
    exit 1
fi

currentDate="$(date '+%Y-%m-%d')"

read -r usageDate usage <<< "$(vnstat -i "$INTERFACE" --oneline | awk -F';' '{print $3, $6}')"

if [ "$usageDate" != "$currentDate" ]; then
    sleep 10m
    continue
fi

unit="$(echo "$usage" | cut -d ' ' -f2)"

if [ "$unit" == "GiB" ]; then
    data="$(echo "$usage" | cut -d ' ' -f1)"

    # if (( $(bc <<< "$data >= 5.00") )); then
    #     notify-send -u critical "Data usage alert" "You have used $usage of data."
    #     mpv --volume=50 "$NET_USAGE_SOUND" 1>/dev/null || notify-send --critical "$0" "$NET_USAGE_SOUND not found."
    #     exit
    # fi

    if (( $(echo "$data >= $THRESHOLD" | bc -l) )); then
        notify-send -u critical "Data usage alert" "You have used $usage of data."
        # mpv --volume=50 "$NET_USAGE_SOUND" >/dev/null 2>&1  || notify-send --critical "$0" "$NET_USAGE_SOUND not found."
        exit
    fi
fi
