#!/usr/bin/env bash

source _scripts_config

router_bat_level () {
    curl -s 'http://192.168.32.1/goform/goform_get_cmd_process?cmd=battery_vol_percent' \
        -H 'Accept: application/json, text/javascript, */*; q=0.01' \
        -H 'Accept-Language: en-US,en;q=0.5' \
        -H 'Accept-Encoding: gzip, deflate' \
        -H 'X-Requested-With: XMLHttpRequest' \
        -H 'Referer: http://192.168.32.1/index.html'
}

level="$(router_bat_level | awk -F'\"' '{ print $4 }')"
file="/tmp/routerbatchecked"

if [ "$level" -lt 25 ]; then
    [ "$(cat $file)" == "checked" ] && exit

    notify-send -u critical -t 43200000 "Low router battery!" "Router battery level is at $level%."
    echo "checked" > "$file"
fi

if [ "$level" -gt 30 ]; then
    echo "unchecked" > "$file"
fi
