#!/usr/bin/env bash

source config

router_bat_level () {
    curl -s 'http://192.168.32.1/goform/goform_get_cmd_process?cmd=battery_vol_percent' \
        -H 'Accept: application/json, text/javascript, */*; q=0.01' \
        -H 'Accept-Language: en-US,en;q=0.5' \
        -H 'Accept-Encoding: gzip, deflate' \
        -H 'X-Requested-With: XMLHttpRequest' \
        -H 'Referer: http://192.168.32.1/index.html'
}

while true
do
    level="$(router_bat_level | awk -F'\"' '{ print $4 }')"

    sleep 5m
done
