#!/usr/bin/env bash

isinstalled fzf || exit

pacman -Slq |
    # fzf -m --preview "cat <(pacman -Si {1}) <(pacman -Fl {1} | awk \"{print \$2}\")" |
    fzf -m --preview "cat <(pacman -Si {1})" |
    xargs -ro sudo pacman -S
