#!/usr/bin/env bash

isinstalled fzf || exit

file=$(pacman -Qq | fzf --reverse)
[ -z "$file" ] && exit

option=$(echo -e "R\\nRn (with configuration files)\\nRs (recursive)\\nRns" | fzf --reverse --header "Chose pacman option:")

case "$option" in
    "R") sudo pacman -Rv "$file" ;;
    "Rn (with configuration files)") sudo pacman -Rnv "$file" ;;
    "Rs (recursive)") sudo pacman -Rsv "$file" ;;
    "Rns") sudo pacman -Rnsv "$file" ;;
    *) exit ;;
esac
