#!/usr/bin/env bash

isinstalled fzf || exit

file=$(pacman -Qq | fzf)
# file=$(pacman -Qq | fzf --reverse)

option=$(echo -e "R\\nRn\\nRs\\nRns" | fzf --header "Chose pacman option:")
# option=$(echo -e "R\\nRn\\nRs\\nRns" | fzf --reverse --header "Chose pacman option:")

case "$option" in
    "R") sudo pacman -R "$file" ;;
    "Rn") sudo pacman -Rn "$file" ;;
    "Rs") sudo pacman -Rs "$file" ;;
    "Rns") sudo pacman -Rns "$file" ;;
esac
