#!/usr/bin/env bash

isinstalled fzf || exit

file=$(pacman -Qq | fzf --reverse)
[ -z "$file" ] && exit

option=$(echo -e "Rns\\nR\\nRs\\nRn" | fzf --reverse --header "Chose pacman option:")

case "$option" in
    "Rns") sudo pacman -Rnsv "$file" ;;
    "R") sudo pacman -Rv "$file" ;;
    "Rs") sudo pacman -Rsv "$file" ;;
    "Rn") sudo pacman -Rnv "$file" ;;
    *) exit ;;
esac
