#!/usr/bin/env bash

isinstalled fd fzf || exit

fzf_min() {
    fzf --reverse --height 10
}

projects_location="$(echo -e "git\ngit new\nlocal\nhttp" | fzf_min)"

case "$projects_location" in
    "git") cd "$HOME/.local/git" || return ;;
    "git new") cd "$HOME/.local/projects/git" || return ;;
    "local") cd "$HOME/.local/projects/local" || return ;;
    "http") cd "/srv/http" || return ;;
    *) return ;;
esac

# # export SKIM_DEFAULT_COMMAND='fd -d 1 --type d'
export FZF_DEFAULT_COMMAND='fd -d 1 --type d'

project="$(fzf_min)"

if [ "$project" ]; then
    cd "$project" || exit 1
    # echo -e "\n\n"
    ls --color=auto -a
    # nvim
fi
