#!/usr/bin/env bash

isinstalled fd fzf || exit

fzf_min() {
    fzf --reverse --height 10
}

projects_location="$(echo -e "git\nlocal\nhttp\nold git" | fzf_min)"

case "$projects_location" in
    "git") cd "$HOME/.local/projects/git" || return ;;
    "local") cd "$HOME/.local/projects/local" || return ;;
    "http") cd "/srv/http" || return ;;
    "old git") cd "$HOME/.local/git" || return ;;
    *) return ;;
esac

# # export SKIM_DEFAULT_COMMAND='fd -d 1 --type d'
export FZF_DEFAULT_COMMAND='fd -d 1 --type d'

project="$(fzf_min)"

if [ "$project" ]; then
    cd "$project" || exit 1
    # echo -e "\n\n"
    ls --color=auto -al
    # nvim
fi
