#!/usr/bin/env bash

isinstalled fzf || exit

dir_location="$(echo -e "git\nlocal\nhttp" | fzf --reverse --height 15)"

case "$dir_location" in
    "git") dir="$HOME/.local/projects/git" ;;
    "local") dir="$HOME/.local/projects/local" ;;
    "http") dir="/srv/http" ;;
    *) exit 0 ;;
esac

selected="$(find "$dir" -mindepth 1 -maxdepth 1 -type d | fzf --reverse --height 15)"

if [[ -z "$selected" ]]; then
    exit 0
fi

selected_name=$(basename "$selected" | tr . _)
tmux_running=$(pgrep tmux)

if [[ -z $TMUX ]] && [[ -z $tmux_running ]]; then
    tmux new-session -s "$selected_name" -c "$selected"
    exit 0
fi

if ! tmux has-session -t="$selected_name" 2> /dev/null; then
    tmux new-session -ds "$selected_name" -c "$selected"
fi

if [[ -z $TMUX ]]; then
    tmux attach -t "$selected_name"
else
    tmux switch-client -t "$selected_name"
fi
