#!/usr/bin/env bash

# shellcheck disable=SC2088

isinstalled fd skim || exit

projectsDir=$(printf "git\nsrc\nsrv" | sk --reverse)

case "$projectsDir" in
    "git") projectsDir="$HOME/.local/git" ;;
    "src") projectsDir="$HOME/.local/src" ;;
    "srv") projectsDir="/srv/http" ;;
    *) exit 1 ;;
esac

export SKIM_DEFAULT_COMMAND='fd -d 1 --type d'
cd "$projectsDir" || exit 1

project=$(sk --reverse)

if [ "$project" ]; then
    cd "$project" || exit 1
    nvim
fi
