#!/usr/bin/env bash

isinstalled fd skim || exit

case "$1" in
    "git") projectsDir="$HOME/.local/git" ;;
    "src") projectsDir="$HOME/.local/src" ;;
    "srv") projectsDir="/srv/http" ;;
    *) exit 1 ;;
esac

# export SKIM_DEFAULT_COMMAND='fd -d 1 --type d'
export FZF_DEFAULT_COMMAND='fd -d 1 --type d'
cd "$projectsDir" || exit 1

project=$(fzf --reverse)

if [ "$project" ]; then
    cd "$project" || exit 1
    # echo -e "\n\n"
    ls --color=auto -al
    # nvim
fi
