#!/usr/bin/env bash

source _scripts_config
isinstalled fd fzf || exit

if [ ! -d "$SCRIPTS_DIR" ]; then
    echo "$SCRIPTS_DIR doesn't exist!"
    exit 1
fi

export FZF_DEFAULT_COMMAND='fd -d 2 --no-ignore'

cd "$SCRIPTS_DIR" || exit 1
script=$(fzf --reverse --height 15)

if [ "$script" ]; then
    nvim "$script" || exit 1
fi
