#!/usr/bin/env bash

isinstalled fd fzf || exit

scriptsDir="$HOME/.local/scripts"

export FZF_DEFAULT_COMMAND='fd -d 2'

cd "$scriptsDir" || exit 1
script=$(fzf --reverse --height 15)

if [ "$script" ]; then
    nvim "$script" || exit 1
fi
