#!/usr/bin/env bash

source config
isinstalled fd fzf || exit

export FZF_DEFAULT_COMMAND='fd -d 2'

cd "$SCRIPTS_DIR" || exit 1
script=$(fzf --reverse --height 15)

if [ "$script" ]; then
    nvim "$script" || exit 1
fi
