#!/usr/bin/env bash

source config
isinstalled fd fzf || exit

dir="$HOME/.local/scripts/personal"

if [ ! -d "$dir" ]; then
    echo "$dir doesn't exist!"
    exit 1
fi

export FZF_DEFAULT_COMMAND='fd -d 2 --no-ignore'

cd "$dir" || exit 1
script=$(fzf --reverse --height 15)

if [ "$script" ]; then
    nvim "$script" || exit 1
fi
