#!/usr/bin/env bash

# shellcheck disable=SC1091

source config
isinstalled shuf nsxiv shuf bluetoothctl || exit

bluetoothConnect(){
    deviceInfo=$(bluetoothctl devices Trusted | $DMENU_V -i -p "Select option:") || exit 1
    deviceMacAddress=$(echo "$deviceInfo" | awk '{print $2}')
    bluetoothctl connect "$deviceMacAddress"
}

case "$(printf "disconnect current device\\nconnect to sony headphones\\nconnect\\nbluetooth status\\nenable bluetooth\\ndisable bluetooth" | $DMENU_V -i -p "Select option:")" in
    "disconnect current device")
        bluetoothctl disconnect
        ;;
    "connect to sony headphones")
        bluetoothctl connect "00:18:09:7F:41:6E"
        ;;
    "connect")
        bluetoothConnect
        ;;
    "bluetooth status")
        notify-send "Bluetooth" "$(bluetoothctl show | grep 'Powered' | sed 's/	//g')."
        ;;
    "enable bluetooth")
        bluetoothctl power on
        notify-send "Bluetooth enabled."
        ;;
    "disable bluetooth")
        bluetoothctl power off
        notify-send "Bluetooth disabled."
        ;;
esac
