#!/usr/bin/env bash

# shellcheck disable=SC1091

source config
isinstalled shuf nsxiv shuf bluetoothctl || exit

bluetooth_connect(){
    deviceInfo=$(bluetoothctl devices Trusted | $DMENU_V -i -p "Select option:") || exit 1
    deviceMacAddress=$(echo "$deviceInfo" | awk '{print $2}')
    bluetoothctl connect "$deviceMacAddress"
}

menu_options="disconnect current device\n"
menu_options+="pair\n"
menu_options+="connect\n"
menu_options+="status\n"
menu_options+="restart\n"
menu_options+="enable bluetooth\n"
menu_options+="disable bluetooth"

selection="$(printf "$menu_options" | $DMENU_V -i -p "Select option:")"

case "$selection" in
    "disconnect current device")
        bluetoothctl disconnect
        ;;
    "pair")
        # TODO: Implement pairing functionality
        # bluetooth_connect
        ;;
    "connect")
        bluetooth_connect
        ;;
    "status")
        status=$(bluetoothctl show | grep 'Powered' | sed 's/	//g')
        notify-send "Bluetooth" "$status."
        ;;
    "restart")
        if sudo systemctl restart bluetooth; then
            notify-send "Bluetooth restarted."
        else
            notify-send "Bluetooth" "Something went wrong."
        fi
        ;;
    "enable bluetooth")
        bluetoothctl power on
        notify-send "Bluetooth enabled."
        ;;
    "disable bluetooth")
        bluetoothctl power off
        notify-send "Bluetooth disabled."
        ;;
esac
