#!/usr/bin/env bash

# shellcheck disable=SC1091

# Gives a dmenu prompt to mount unmounted drives. If they're in /etc/fstab, 
# they'll be mounted automatically. Otherwise, you'll be prompted to give a 
# mountpoint from already existsing directories. If you input a novel directory, 
# it will prompt you to create that directory.

source config

getmount() { \
	[ -z "$chosen" ] && exit 1
        # shellcheck disable=SC2086
	mp="$(find $1 2>/dev/null | $DMENU -i -p "Type in mount point.")" || exit 1
	[ "$mp" = "" ] && exit 1
	if [ ! -d "$mp" ]; then
		mkdiryn=$(printf "No\\nYes" | $DMENU -i -p "$mp does not exist. Create it?") || exit 1
		[ "$mkdiryn" = "Yes" ] && (mkdir -p "$mp" || sudo -A mkdir -p "$mp")
	fi
	}

mountusb() { \
	chosen="$(echo "$usbdrives" | $DMENU -i -p "Mount which drive?")" || exit 1
	chosen="$(echo "$chosen" | awk '{print $1}')"

	sudo -A mount "$chosen" 2>/dev/null && notify-send "Mount" "$chosen mounted." && exit 0

	alreadymounted=$(lsblk -nrpo "name,type,mountpoint" | awk '$3!~/\/boot|\/home$|SWAP/&&length($3)>1{printf "-not ( -path *%s -prune ) ",$3}')

	getmount "/home/$USER/mnt -maxdepth 5 -type d $alreadymounted"

	partitiontype="$(lsblk -no "fstype" "$chosen")"

	case "$partitiontype" in
		"vfat") sudo -A mount -t vfat "$chosen" "$mp" -o rw,umask=0000;;
		"exfat") sudo -A mount "$chosen" "$mp" -o uid="$(id -u)",gid="$(id -g)";;
		*) sudo -A mount "$chosen" "$mp"; user="$(whoami)"; ug="$(groups | awk '{print $1}')"; sudo -A chown "$user":"$ug" "$mp";;
	esac

	notify-send "Mount" "$chosen mounted to $mp."
	}


usbdrives="$(lsblk -rpo "name,type,size,mountpoint" | grep 'part\|rom' | grep -v '/dev/sda2' | awk '$4==""{printf "%s (%s)\n",$1,$3}')"

if [ -z "$usbdrives" ]; then
	notify-send "Mount" "No device detected." && exit
else
    echo "USB drive(s) detected."
    mountusb
fi
