#!/usr/bin/env bash

# shellcheck disable=SC1091

source _scripts_config

case "$(printf "lock\\nturn screen off\\nrebuild moonwm\\nlogout\\nreboot\\npoweroff" | $DMENU -i )" in
    "lock")
        isinstalled xsecurelock || exit

        export XSECURELOCK_NO_COMPOSITE=1
        # export XSECURELOCK_COMPOSITE_OBSCURER=0
        export XSECURELOCK_PASSWORD_PROMPT="time_hex"
        export XSECURELOCK_DISCARD_FIRST_KEYPRESS=0
        export XSECURELOCK_BLANK_DPMS_STATE="on"
        export XSECURELOCK_BLANK_TIMEOUT=-1
        isinstalled xcompmgr || exit
        pgrep ! -f xcompmgr >/dev/null || killall -9 xcompmgr
        xsecurelock
        pgrep -f xcompmgr >/dev/null || xcompmgr &
        ;;
    "turn screen off") sleep 1s; xset dpms force off & ;;
    # "rebuild dwm") rebuild dwm ;;
    "rebuild moonwm") rebuild moonwm ;;
    "logout") pkill X ;;
    # "leave i3") kill -TERM "$(pgrep -u "$USER" "\bi3$")" ;;
    # "leave awesome") kill -TERM "$(pgrep -u "$USER" "\bawesome$")" ;;
    "reboot") systemctl reboot -i ;;
    "poweroff")
        sudo systemctl poweroff -i --output=verbose
        ;;
    *) exit 1 ;;
esac
