#!/usr/bin/env bash

# shellcheck disable=SC1091

source config

# case "$(printf "turn screen off\\nlock\\nrebuild moonwm\\nlogout\\nreboot\\npoweroff" | $DMENU -i )" in
case "$(printf "lock\\nturn screen off\\nrebuild moonwm\\nlogout\\nreboot\\npoweroff" | $DMENU -i )" in
    "lock")
        isinstalled xsecurelock || exit

        export XSECURELOCK_NO_COMPOSITE=1
        # export XSECURELOCK_COMPOSITE_OBSCURER=0
        export XSECURELOCK_PASSWORD_PROMPT="asterisks"
        export XSECURELOCK_DISCARD_FIRST_KEYPRESS=0
        killall -9 xcompmgr
        xsecurelock
        xcompmgr &
        ;;
    "turn screen off") xset dpms force off ;;
    # "rebuild dwm") rebuild dwm ;;
    "rebuild moonwm") rebuild moonwm ;;
    "logout") pkill X ;;
    # "leave i3") kill -TERM "$(pgrep -u "$USER" "\bi3$")" ;;
    # "leave awesome") kill -TERM "$(pgrep -u "$USER" "\bawesome$")" ;;
    "reboot") systemctl reboot -i ;;
    "poweroff") systemctl poweroff -i ;;
    *) exit 1 ;;
esac
