#!/usr/bin/env bash

# shellcheck disable=SC1091

source _scripts_config
isinstalled nmcli || exit

set -euo pipefail

main() {
    bssid=$(nmcli device wifi list | sed -n '1!p' | cut -b 9- | $DMENU_V -i -p "Select network:" | cut -d' ' -f1)
    pass=$(printf "" | $DMENU_V -i -p "Enter password:")
    # We are disabling a shellcheck warning about using && and || as it doesn't apply here.
    # shellcheck disable=SC2015
    [ -n "$pass" ] && nmcli device wifi connect "$bssid" password "$pass" || nmcli device wifi connect "$bssid"
    sleep 10
    if ping -q -c 2 -W 2 google.com >/dev/null; then
        notify-send "Internet is working."
    else
        notify-send "Internet is not working."
    fi
}

[[ "${BASH_SOURCE[0]}" == "${0}" ]] && main "$@"
