#!/usr/bin/env bash

# shellcheck disable=SC1091

source config
isinstalled xdotool || exit

# getSite="$(grep -v '^#' $HOME/doc/bookmarks/sites.md | dmenu -i -l 25 | cut -d' ' -f1)"

getSite() {
  # grep -v '^#' $XDG_DOCUMENTS_DIR/bookmarks/sites.md |
  # sed 1,1d "$XDG_DOCUMENTS_DIR/bookmarks/sites.md" |
  # cat "$XDG_DOCUMENTS_DIR/bookmarks/sites.md" |
    $DMENU_V -i < "$XDG_DOCUMENTS_DIR/bookmarks/bookmarks.md" |
        cut -d' ' -f1
}

xdotool type "$(getSite)"
