#!/usr/bin/env bash

# shellcheck disable=SC1091

source _scripts_config
isinstalled xdotool || exit

# getSite="$(grep -v '^#' $HOME/.local/web/bookmarks/sites.md | dmenu -i -l 25 | cut -d' ' -f1)"

getSite() {
  # grep -v '^#' $HOME/.local/web/bookmarks/sites.md |
  # sed 1,1d "$HOME/.local/web/bookmarks/sites.md" |
  # cat "$HOME/.local/web/bookmarks/sites.md" |
    $DMENU_V -i < "$HOME/doc/bookmarks.md" |
        cut -d' ' -f1
}

xdotool type "$(getSite)"
