#!/usr/bin/env bash

isinstalled xclip translate || exit

xclip -out -selection clipboard > /tmp/clipboard
sed -i "s/[-*/\!@#$%{}^&*()_+>'\"-<:-=~|]//g;s/\[//g;s/\]//g" /tmp/clipboard
translate -s en -t pl "$(cat /tmp/clipboard)" | xclip -selection clipboard
notify-send "Translate" "$(xclip -out -selection clipboard)"
