#!/bin/sh

notify-send "Type password 1."
sleep 1s
echo RELOADAGENT | gpg-connect-agent &> /dev/null
gpg -d $HOME/tmp/passreminders/password1.gpg

asd=`echo $?`
[[ $asd != 0 ]] && notify-send "Wrong password."

echo RELOADAGENT | gpg-connect-agent &> /dev/null
