#!/usr/bin/env bash

isinstalled fd skim || exit

case "$1" in
    "git") dir="$HOME/.local/git" ;;
    "src") dir="$HOME/.local/src" ;;
    "srv") dir="/srv/http" ;;
    *) exit 1 ;;
esac

export SKIM_DEFAULT_COMMAND='fd -d 1 --type d'
cd "$dir" || exit 1
cd "$(sk --reverse)" || exit 1
