#!/usr/bin/env bash

# shellcheck disable=SC2088

isinstalled fd skim || exit

projectsDir=$(printf "~/.local/git\n~/.local/src\nsrv/http" | sk --reverse)

case "$projectsDir" in
    "~/.local/git") projectsDir="$HOME/.local/git" ;;
    "~/.local/src") projectsDir="$HOME/.local/src" ;;
    "srv") projectsDir="/srv/http" ;;
    *) exit 1 ;;
esac

export SKIM_DEFAULT_COMMAND='fd -d 1 --type d'
cd "$projectsDir" || exit 1

project=$(sk --reverse)

if [ "$project" ]; then
    cd "$project" || exit 1
    nvim .
fi
